<?php

declare(strict_types=1);

return [
    'vehicles' => [
        'striker' => [
            'name' => 'Striker',
            'role' => 'Interceptor',
            'description' => 'Fast, agile fighter drone with high-velocity plasma blasters and accelerated dash recovery. Lower armor.',
            'speed' => 1.35,
            'max_health' => 80,
            'max_energy' => 100,
            'energy_regen' => 20,
            'dash_cost' => 30,
            'dash_cooldown' => 1.2,
            'weapon_type' => 'plasma_rapid',
            'damage' => 18,
            'fire_rate' => 0.18,
            'special_name' => 'Overdrive',
            'special_description' => 'Supercharges fire rate by 60% and increases speed for 4 seconds.',
            'special_duration' => 4.0,
            'special_cooldown' => 14.0,
            'special_cost' => 60,
            'model_color' => 0x00f0ff,
        ],
        'titan' => [
            'name' => 'Titan',
            'role' => 'Juggernaut',
            'description' => 'Heavy assault craft engineered for maximum survivability with kinetic shield absorption and siege mortar blast.',
            'speed' => 0.85,
            'max_health' => 160,
            'max_energy' => 120,
            'energy_regen' => 15,
            'dash_cost' => 45,
            'dash_cooldown' => 2.2,
            'weapon_type' => 'heavy_cannon',
            'damage' => 55,
            'fire_rate' => 0.65,
            'special_name' => 'Kinetic Dome',
            'special_description' => 'Deploys an impenetrable spherical forcefield absorbing all incoming damage for 3.5 seconds.',
            'special_duration' => 3.5,
            'special_cooldown' => 18.0,
            'special_cost' => 70,
            'model_color' => 0xff3b00,
        ],
        'phantom' => [
            'name' => 'Phantom',
            'role' => 'Infiltrator',
            'description' => 'High-mobility phase craft equipped with quantum dash technology and piercing coherent phase beams.',
            'speed' => 1.15,
            'max_health' => 100,
            'max_energy' => 110,
            'energy_regen' => 22,
            'dash_cost' => 25,
            'dash_cooldown' => 0.9,
            'weapon_type' => 'phase_beam',
            'damage' => 28,
            'fire_rate' => 0.32,
            'special_name' => 'Phase Shift',
            'special_description' => 'Shifts into subspace, becoming invulnerable and damaging all hostile drones along your trajectory.',
            'special_duration' => 2.2,
            'special_cooldown' => 12.0,
            'special_cost' => 50,
            'model_color' => 0xbf00ff,
        ],
    ],

    'arenas' => [
        'neon_core' => [
            'id' => 'neon_core',
            'name' => 'Neon Core',
            'subtitle' => 'Sub-Grid 07 // Cybernetic Bastion',
            'description' => 'Reflective cyber-grid flanked by pulsed energy pillars, rotating laser barriers, and kinetic speed acceleration gates.',
            'radius' => 50,
            'ambient_color' => 0x07111e,
            'fog_color' => 0x050811,
            'grid_color' => 0x00f0ff,
            'hazards' => ['laser_barriers', 'overload_nodes'],
            'obstacles_count' => 10,
        ],
        'orbital_station' => [
            'id' => 'orbital_station',
            'name' => 'Orbital Station',
            'subtitle' => 'Aegis Platform 9 // Void Horizon',
            'description' => 'Zero-gravity space station platform with floating asteroid clusters, repulsion vortexes, and open void perimeters.',
            'radius' => 55,
            'ambient_color' => 0x0a0518,
            'fog_color' => 0x030208,
            'grid_color' => 0x9d4edd,
            'hazards' => ['repulsion_wells', 'floating_debris'],
            'obstacles_count' => 12,
        ],
        'magma_foundry' => [
            'id' => 'magma_foundry',
            'name' => 'Magma Foundry',
            'subtitle' => 'Obsidian Crater // Core Sector',
            'description' => 'Volcanic extraction facility featuring molten lava trenches that inflict rapid burn damage and steam vents.',
            'radius' => 48,
            'ambient_color' => 0x1a0604,
            'fog_color' => 0x0c0302,
            'grid_color' => 0xff4800,
            'hazards' => ['lava_trenches', 'steam_eruptions'],
            'obstacles_count' => 14,
        ],
    ],

    'difficulties' => [
        'easy' => [
            'id' => 'easy',
            'name' => 'Recruit',
            'ai_reaction_time' => 0.7,
            'ai_aim_accuracy' => 0.65,
            'ai_speed_mult' => 0.8,
            'ai_health_mult' => 0.8,
            'ai_damage_mult' => 0.7,
            'score_multiplier' => 1.0,
            'spawn_rate_seconds' => 4.0,
            'max_concurrent_enemies' => 4,
        ],
        'normal' => [
            'id' => 'normal',
            'name' => 'Veteran',
            'ai_reaction_time' => 0.4,
            'ai_aim_accuracy' => 0.85,
            'ai_speed_mult' => 1.0,
            'ai_health_mult' => 1.0,
            'ai_damage_mult' => 1.0,
            'score_multiplier' => 1.5,
            'spawn_rate_seconds' => 3.0,
            'max_concurrent_enemies' => 6,
        ],
        'hard' => [
            'id' => 'hard',
            'name' => 'Void Master',
            'ai_reaction_time' => 0.18,
            'ai_aim_accuracy' => 0.96,
            'ai_speed_mult' => 1.2,
            'ai_health_mult' => 1.25,
            'ai_damage_mult' => 1.3,
            'score_multiplier' => 2.5,
            'spawn_rate_seconds' => 2.0,
            'max_concurrent_enemies' => 8,
        ],
    ],

    'anti_cheat' => [
        'token_lifetime_seconds' => 600, // 10 minutes max match run
        'min_match_duration' => 25, // At least 25 seconds for a legitimate match
        'max_match_duration' => 360, // 6 minutes max
        'clock_drift_tolerance_seconds' => 15,
        'max_score_per_second' => 280, // Absolute maximum theoretical point throughput
        'max_kills_per_second' => 1.8,
        'max_combo_multiplier' => 5,
        'require_monotonic_telemetry' => true,
    ],
];
